name: URLs

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install awesome_bot
        run: gem install awesome_bot
      - name: Check URLs
        run: awesome_bot readme.md --allow-redirect --allow 403 --request-delay 0.2
